blank_issues_enabled: false

contact_links:
  - name: ğŸ› Report a bug or propose a fix
    url: https://github.com/buildermethods/design-os/discussions/categories/bugs
    about: Already checked the docs and found a reproducible bug? Please report it in the 'Bugs' discussion area.

  - name: ğŸ’¡ Feature request or idea
    url: https://github.com/buildermethods/design-os/discussions/categories/ideas
    about: Request new features, integrations, or other improvements in the 'Ideas' discussion area.

  - name: â“ Ask a question
    url: https://github.com/buildermethods/design-os/discussions/categories/q-a
    about: For community support and general questions, use the 'Q&A' discussion area.

  - name: ğŸ¯ Member support request
    url: https://buildermethods.com/pro
    about: Join Builder Methods Pro for official Design OS support with guaranteed responses from Brian & team, plus access to community chat, workshops, courses and more.

  - name: ğŸ“— Check the official docs
    url: https://buildermethods.com/design-os
    about: Please review the docs before posting a bug, question, or idea.
